import { Meter } from '../../@types';

export const FAKE: Omit<Meter, 'area'>[] = [
  {
    id: '1',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '2',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '3',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '4',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '5',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '6',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '7',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '8',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '9',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '10',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '11',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '12',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '13',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '14',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '15',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '16',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '17',
    _type: ['HotWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '18',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '19',
    _type: ['ColdWaterAreaMeter'],

    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
  {
    id: '20',
    _type: ['ColdWaterAreaMeter'],
    is_automatic: false,
    communication: 'smhg',
    description: 'smhg',
    serial_number: 'smhg',
    installation_date: '10.10.2022',
    brand_name: 'smhg',
    model_name: 'smhg',
    initial_values: [333467.6636],
  },
];
